#!/bin/sh

pulsemixer --get-mute | grep 0 >/dev/null && echo "<span foreground='#74c7ec' size='large'></span> <span size='small' rise='2pt'>$(pulsemixer --get-volume | awk '{print $1}')%</span>" || echo "<span foreground='#eba0ac' size='large'>󰝟</span>"
